### ISSUE TITLE
DB source to beta checklist

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#227]
- [ ] Add to FEATURES.md
- [ ] Support concurrency and load-balancing across replicas.
- [ ] Add to Python SDK
- [ ] Write FMEA and stress tests
- [ ] Add an example
